import { useState } from 'react'
import {
  Check,
  Copy,
  Network,
  Plus,
  RotateCcw,
  Trash2,
} from 'lucide-react'

interface BridgePort {
  id: number
  interfaceName: string
  pvid: string
  ingressFiltering: boolean
}

const defaultPorts: BridgePort[] = [
  {
    id: 1,
    interfaceName: 'ether2',
    pvid: '1',
    ingressFiltering: true,
  },
  {
    id: 2,
    interfaceName: 'ether3',
    pvid: '1',
    ingressFiltering: true,
  },
]

function BridgeGenerator() {
  const [bridgeName, setBridgeName] = useState('bridge')
  const [protocolMode, setProtocolMode] = useState<
    'rstp' | 'stp' | 'none'
  >('rstp')
  const [vlanFiltering, setVlanFiltering] = useState(true)
  const [fastForward, setFastForward] = useState(true)
  const [ports, setPorts] = useState<BridgePort[]>(defaultPorts)

  const [interfaceName, setInterfaceName] = useState('')
  const [pvid, setPvid] = useState('1')
  const [ingressFiltering, setIngressFiltering] = useState(true)
  const [copied, setCopied] = useState(false)

  function addPort() {
    const interfaceValue = interfaceName.trim()
    const pvidValue = pvid.trim()

    if (!interfaceValue || !pvidValue) {
      return
    }

    if (
      ports.some(
        (port) => port.interfaceName === interfaceValue,
      )
    ) {
      return
    }

    setPorts((current) => [
      ...current,
      {
        id: Date.now(),
        interfaceName: interfaceValue,
        pvid: pvidValue,
        ingressFiltering,
      },
    ])

    setInterfaceName('')
    setPvid('1')
    setIngressFiltering(true)
  }

  function removePort(id: number) {
    setPorts((current) =>
      current.filter((port) => port.id !== id),
    )
  }

  function reset() {
    setBridgeName('bridge')
    setProtocolMode('rstp')
    setVlanFiltering(true)
    setFastForward(true)
    setPorts(defaultPorts)
    setInterfaceName('')
    setPvid('1')
    setIngressFiltering(true)
    setCopied(false)
  }

  const config = [
    '# MikroTik Bridge Configuration',
    '# Generated by NetForge',
    '',
    '/interface bridge',
    `add name=${bridgeName || 'bridge'} protocol-mode=${protocolMode} vlan-filtering=${vlanFiltering ? 'yes' : 'no'} fast-forward=${fastForward ? 'yes' : 'no'}`,
    '',
    '/interface bridge port',
    ...ports.map(
      (port) =>
        `add bridge=${bridgeName || 'bridge'} interface=${port.interfaceName} pvid=${port.pvid} ingress-filtering=${port.ingressFiltering ? 'yes' : 'no'}`,
    ),
  ].join('\n')

  async function copyConfig() {
    await navigator.clipboard.writeText(config)
    setCopied(true)

    setTimeout(() => {
      setCopied(false)
    }, 2000)
  }

  return (
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-teal-500/10 text-teal-400">
            <Network size={20} />
          </div>

          <div>
            <h2 className="font-semibold text-white">
              Bridge Generator
            </h2>

            <p className="text-xs text-slate-500">
              Generate MikroTik bridge and bridge-port configuration.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={reset}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs font-medium text-slate-400 transition hover:border-slate-600 hover:text-white"
        >
          <RotateCcw size={14} />
          Reset
        </button>
      </div>

      <div className="grid gap-6 p-5 lg:grid-cols-2">
        <div>
          <h3 className="text-sm font-semibold text-white">
            Bridge Settings
          </h3>

          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            <div className="sm:col-span-2">
              <label
                htmlFor="mikrotik-bridge-name"
                className="mb-2 block text-sm font-medium text-slate-300"
              >
                Bridge Name
              </label>

              <input
                id="mikrotik-bridge-name"
                value={bridgeName}
                onChange={(event) =>
                  setBridgeName(event.target.value)
                }
                placeholder="bridge"
                className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />
            </div>
          </div>

          <div className="mt-5">
            <span className="mb-2 block text-sm font-medium text-slate-300">
              Protocol Mode
            </span>

            <div className="grid grid-cols-3 gap-2">
              {[
                ['rstp', 'RSTP'],
                ['stp', 'STP'],
                ['none', 'None'],
              ].map(([value, label]) => (
                <button
                  key={value}
                  type="button"
                  onClick={() =>
                    setProtocolMode(
                      value as 'rstp' | 'stp' | 'none',
                    )
                  }
                  className={[
                    'rounded-lg border px-3 py-2.5 text-xs font-medium transition',
                    protocolMode === value
                      ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                      : 'border-slate-700 text-slate-400 hover:text-white',
                  ].join(' ')}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>

          <div className="mt-5 grid grid-cols-2 gap-2">
            <button
              type="button"
              onClick={() => setVlanFiltering(true)}
              className={[
                'rounded-lg border px-3 py-2.5 text-sm font-medium transition',
                vlanFiltering
                  ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                  : 'border-slate-700 text-slate-400 hover:text-white',
              ].join(' ')}
            >
              VLAN Filtering On
            </button>

            <button
              type="button"
              onClick={() => setVlanFiltering(false)}
              className={[
                'rounded-lg border px-3 py-2.5 text-sm font-medium transition',
                !vlanFiltering
                  ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                  : 'border-slate-700 text-slate-400 hover:text-white',
              ].join(' ')}
            >
              VLAN Filtering Off
            </button>
          </div>

          <div className="mt-3">
            <button
              type="button"
              onClick={() => setFastForward((current) => !current)}
              className={[
                'w-full rounded-lg border px-3 py-2.5 text-sm font-medium transition',
                fastForward
                  ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                  : 'border-slate-700 text-slate-400 hover:text-white',
              ].join(' ')}
            >
              Fast Forward: {fastForward ? 'Enabled' : 'Disabled'}
            </button>
          </div>

          <div className="mt-6">
            <h3 className="text-sm font-semibold text-white">
              Bridge Ports
            </h3>

            <div className="mt-3 grid gap-3 sm:grid-cols-2">
              <input
                value={interfaceName}
                onChange={(event) =>
                  setInterfaceName(event.target.value)
                }
                onKeyDown={(event) => {
                  if (event.key === 'Enter') {
                    addPort()
                  }
                }}
                placeholder="ether4"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />

              <input
                value={pvid}
                onChange={(event) =>
                  setPvid(event.target.value)
                }
                placeholder="PVID 1"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />
            </div>

            <div className="mt-3">
              <button
                type="button"
                onClick={() =>
                  setIngressFiltering(
                    (current) => !current,
                  )
                }
                className={[
                  'w-full rounded-lg border px-3 py-2.5 text-sm font-medium transition',
                  ingressFiltering
                    ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                    : 'border-slate-700 text-slate-400 hover:text-white',
                ].join(' ')}
              >
                Ingress Filtering:{' '}
                {ingressFiltering ? 'Enabled' : 'Disabled'}
              </button>
            </div>

            <button
              type="button"
              onClick={addPort}
              className="mt-3 inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
            >
              <Plus size={16} />
              Add Port
            </button>
          </div>

          <div className="mt-5 space-y-2">
            {ports.map((port) => (
              <div
                key={port.id}
                className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950 px-3 py-3"
              >
                <div className="min-w-0">
                  <p className="font-mono text-sm text-teal-400">
                    {port.interfaceName}
                  </p>

                  <p className="mt-1 text-xs text-slate-500">
                    PVID {port.pvid} · ingress filtering{' '}
                    {port.ingressFiltering ? 'on' : 'off'}
                  </p>
                </div>

                <button
                  type="button"
                  onClick={() => removePort(port.id)}
                  className="shrink-0 text-slate-500 transition hover:text-red-400"
                  title="Remove port"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-950">
          <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
            <div>
              <h3 className="text-sm font-semibold text-white">
                Generated RouterOS
              </h3>

              <p className="text-xs text-slate-500">
                Ready to paste into MikroTik RouterOS terminal.
              </p>
            </div>

            <button
              type="button"
              onClick={copyConfig}
              className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-400"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <pre className="max-h-[650px] overflow-auto p-4 font-mono text-xs leading-6 text-slate-300">
            <code>{config}</code>
          </pre>
        </div>
      </div>
    </section>
  )
}

export default BridgeGenerator
