import { useState } from 'react'
import {
  Check,
  Copy,
  Plus,
  RotateCcw,
  Shield,
  Trash2,
} from 'lucide-react'

interface FirewallRule {
  id: number
  chain: 'input' | 'forward' | 'output'
  action: 'accept' | 'drop' | 'reject' | 'log'
  protocol: 'tcp' | 'udp' | 'icmp' | 'any'
  srcAddress: string
  dstAddress: string
  srcPort: string
  dstPort: string
  inInterface: string
  outInterface: string
  comment: string
}

const defaultRules: FirewallRule[] = [
  {
    id: 1,
    chain: 'input',
    action: 'accept',
    protocol: 'icmp',
    srcAddress: '',
    dstAddress: '',
    srcPort: '',
    dstPort: '',
    inInterface: '',
    outInterface: '',
    comment: 'Allow ICMP',
  },
  {
    id: 2,
    chain: 'input',
    action: 'accept',
    protocol: 'tcp',
    srcAddress: '',
    dstAddress: '',
    srcPort: '',
    dstPort: '22',
    inInterface: '',
    outInterface: '',
    comment: 'Allow SSH',
  },
  {
    id: 3,
    chain: 'forward',
    action: 'accept',
    protocol: 'any',
    srcAddress: '192.168.88.0/24',
    dstAddress: '',
    srcPort: '',
    dstPort: '',
    inInterface: 'bridge',
    outInterface: 'ether1',
    comment: 'Allow LAN Internet',
  },
]

function FirewallGenerator() {
  const [rules, setRules] = useState<FirewallRule[]>(defaultRules)
  const [chain, setChain] = useState<
    'input' | 'forward' | 'output'
  >('input')
  const [action, setAction] = useState<
    'accept' | 'drop' | 'reject' | 'log'
  >('accept')
  const [protocol, setProtocol] = useState<
    'tcp' | 'udp' | 'icmp' | 'any'
  >('tcp')
  const [srcAddress, setSrcAddress] = useState('')
  const [dstAddress, setDstAddress] = useState('')
  const [srcPort, setSrcPort] = useState('')
  const [dstPort, setDstPort] = useState('')
  const [inInterface, setInInterface] = useState('')
  const [outInterface, setOutInterface] = useState('')
  const [comment, setComment] = useState('')
  const [copied, setCopied] = useState(false)

  function addRule() {
    if (
      !srcAddress.trim() &&
      !dstAddress.trim() &&
      !srcPort.trim() &&
      !dstPort.trim() &&
      !inInterface.trim() &&
      !outInterface.trim() &&
      !comment.trim()
    ) {
      return
    }

    const rule: FirewallRule = {
      id: Date.now(),
      chain,
      action,
      protocol,
      srcAddress: srcAddress.trim(),
      dstAddress: dstAddress.trim(),
      srcPort: srcPort.trim(),
      dstPort: dstPort.trim(),
      inInterface: inInterface.trim(),
      outInterface: outInterface.trim(),
      comment: comment.trim(),
    }

    setRules((current) => [...current, rule])

    setSrcAddress('')
    setDstAddress('')
    setSrcPort('')
    setDstPort('')
    setInInterface('')
    setOutInterface('')
    setComment('')
  }

  function removeRule(id: number) {
    setRules((current) => current.filter((rule) => rule.id !== id))
  }

  function reset() {
    setRules(defaultRules)
    setChain('input')
    setAction('accept')
    setProtocol('tcp')
    setSrcAddress('')
    setDstAddress('')
    setSrcPort('')
    setDstPort('')
    setInInterface('')
    setOutInterface('')
    setComment('')
    setCopied(false)
  }

  function buildRule(rule: FirewallRule) {
    const parts = [
      `/ip firewall filter add chain=${rule.chain}`,
      `action=${rule.action}`,
    ]

    if (rule.protocol !== 'any') {
      parts.push(`protocol=${rule.protocol}`)
    }

    if (rule.srcAddress) {
      parts.push(`src-address=${rule.srcAddress}`)
    }

    if (rule.dstAddress) {
      parts.push(`dst-address=${rule.dstAddress}`)
    }

    if (rule.srcPort) {
      parts.push(`src-port=${rule.srcPort}`)
    }

    if (rule.dstPort) {
      parts.push(`dst-port=${rule.dstPort}`)
    }

    if (rule.inInterface) {
      parts.push(`in-interface=${rule.inInterface}`)
    }

    if (rule.outInterface) {
      parts.push(`out-interface=${rule.outInterface}`)
    }

    if (rule.comment) {
      parts.push(`comment="${rule.comment.replace(/"/g, '')}"`)
    }

    return parts.join(' ')
  }

  const config = [
    '# MikroTik Firewall Filter Configuration',
    '# Generated by NetForge',
    '',
    ...rules.map(buildRule),
  ].join('\n')

  async function copyConfig() {
    await navigator.clipboard.writeText(config)
    setCopied(true)

    setTimeout(() => {
      setCopied(false)
    }, 2000)
  }

  return (
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-red-500/10 text-red-400">
            <Shield size={20} />
          </div>

          <div>
            <h2 className="font-semibold text-white">
              Firewall Generator
            </h2>

            <p className="text-xs text-slate-500">
              Generate MikroTik firewall filter rules for input, forward, and output traffic.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={reset}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs font-medium text-slate-400 transition hover:border-slate-600 hover:text-white"
        >
          <RotateCcw size={14} />
          Reset
        </button>
      </div>

      <div className="grid min-w-0 gap-6 p-5 lg:grid-cols-2">
        <div className="min-w-0">
          <h3 className="text-sm font-semibold text-white">
            Firewall Rule
          </h3>

          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            <div>
              <span className="mb-2 block text-sm font-medium text-slate-300">
                Chain
              </span>

              <div className="grid grid-cols-3 gap-2">
                {(['input', 'forward', 'output'] as const).map(
                  (value) => (
                    <button
                      key={value}
                      type="button"
                      onClick={() => setChain(value)}
                      className={[
                        'rounded-lg border px-2 py-2.5 text-xs font-medium transition',
                        chain === value
                          ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                          : 'border-slate-700 text-slate-400 hover:text-white',
                      ].join(' ')}
                    >
                      {value}
                    </button>
                  ),
                )}
              </div>
            </div>

            <div>
              <span className="mb-2 block text-sm font-medium text-slate-300">
                Action
              </span>

              <div className="grid grid-cols-4 gap-2">
                {(
                  ['accept', 'drop', 'reject', 'log'] as const
                ).map((value) => (
                  <button
                    key={value}
                    type="button"
                    onClick={() => setAction(value)}
                    className={[
                      'rounded-lg border px-2 py-2.5 text-xs font-medium transition',
                      action === value
                        ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                        : 'border-slate-700 text-slate-400 hover:text-white',
                    ].join(' ')}
                  >
                    {value}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="mt-5">
            <label
              htmlFor="mikrotik-firewall-protocol"
              className="mb-2 block text-sm font-medium text-slate-300"
            >
              Protocol
            </label>

            <select
              id="mikrotik-firewall-protocol"
              value={protocol}
              onChange={(event) =>
                setProtocol(
                  event.target.value as
                    | 'tcp'
                    | 'udp'
                    | 'icmp'
                    | 'any',
                )
              }
              className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-500"
            >
              <option value="any">Any Protocol</option>
              <option value="tcp">TCP</option>
              <option value="udp">UDP</option>
              <option value="icmp">ICMP</option>
            </select>
          </div>

          <div className="mt-5 grid gap-3 sm:grid-cols-2">
            <input
              value={srcAddress}
              onChange={(event) => setSrcAddress(event.target.value)}
              placeholder="Source address"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={dstAddress}
              onChange={(event) => setDstAddress(event.target.value)}
              placeholder="Destination address"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={srcPort}
              onChange={(event) => setSrcPort(event.target.value)}
              placeholder="Source port"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={dstPort}
              onChange={(event) => setDstPort(event.target.value)}
              placeholder="Destination port"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={inInterface}
              onChange={(event) => setInInterface(event.target.value)}
              placeholder="In interface e.g. bridge"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={outInterface}
              onChange={(event) => setOutInterface(event.target.value)}
              placeholder="Out interface e.g. ether1"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={comment}
              onChange={(event) => setComment(event.target.value)}
              placeholder="Rule comment"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500 sm:col-span-2"
            />
          </div>

          <button
            type="button"
            onClick={addRule}
            className="mt-4 inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
          >
            <Plus size={16} />
            Add Firewall Rule
          </button>

          <div className="mt-5 space-y-2">
            {rules.map((rule) => (
              <div
                key={rule.id}
                className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950 px-3 py-3"
              >
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="rounded-md bg-red-500/10 px-2 py-1 text-xs font-medium text-red-400">
                      {rule.chain}
                    </span>

                    <span className="font-mono text-xs text-slate-400">
                      {rule.action}
                    </span>
                  </div>

                  <p className="mt-2 truncate font-mono text-xs text-slate-500">
                    {buildRule(rule)}
                  </p>
                </div>

                <button
                  type="button"
                  onClick={() => removeRule(rule.id)}
                  className="shrink-0 text-slate-500 transition hover:text-red-400"
                  title="Remove firewall rule"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-950">
          <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
            <div>
              <h3 className="text-sm font-semibold text-white">
                Generated RouterOS
              </h3>

              <p className="text-xs text-slate-500">
                Ready to paste into MikroTik RouterOS terminal.
              </p>
            </div>

            <button
              type="button"
              onClick={copyConfig}
              className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-400"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <pre className="max-h-[650px] overflow-auto p-4 font-mono text-xs leading-6 text-slate-300">
            <code>{config}</code>
          </pre>
        </div>
      </div>
    </section>
  )
}

export default FirewallGenerator
