import { useState } from 'react'
import {
  Check,
  Copy,
  Globe,
  Plus,
  RotateCcw,
  Trash2,
} from 'lucide-react'

interface UserEntry {
  id: number
  name: string
  password: string
  profile: string
  limitUptime: string
}

const defaultUsers: UserEntry[] = [
  {
    id: 1,
    name: 'user1',
    password: '123456',
    profile: 'default',
    limitUptime: '1h',
  },
  {
    id: 2,
    name: 'user2',
    password: '123456',
    profile: 'default',
    limitUptime: '2h',
  },
]

function HotspotGenerator() {
  const [interfaceName, setInterfaceName] = useState('bridge')
  const [addressPool, setAddressPool] = useState('10.10.10.10-10.10.10.254')
  const [gateway, setGateway] = useState('10.10.10.1')
  const [dnsName, setDnsName] = useState('hotspot.local')
  const [profileName, setProfileName] = useState('default')
  const [users, setUsers] = useState<UserEntry[]>(defaultUsers)

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [limitUptime, setLimitUptime] = useState('')
  const [userProfile, setUserProfile] = useState('default')
  const [copied, setCopied] = useState(false)

  function addUser() {
    const nameValue = username.trim()
    const passwordValue = password.trim()
    const profileValue = userProfile.trim() || 'default'
    const uptimeValue = limitUptime.trim()

    if (!nameValue || !passwordValue) {
      return
    }

    if (users.some((user) => user.name === nameValue)) {
      return
    }

    setUsers((current) => [
      ...current,
      {
        id: Date.now(),
        name: nameValue,
        password: passwordValue,
        profile: profileValue,
        limitUptime: uptimeValue,
      },
    ])

    setUsername('')
    setPassword('')
    setLimitUptime('')
    setUserProfile('default')
  }

  function removeUser(id: number) {
    setUsers((current) =>
      current.filter((user) => user.id !== id),
    )
  }

  function reset() {
    setInterfaceName('bridge')
    setAddressPool('10.10.10.10-10.10.10.254')
    setGateway('10.10.10.1')
    setDnsName('hotspot.local')
    setProfileName('default')
    setUsers(defaultUsers)
    setUsername('')
    setPassword('')
    setLimitUptime('')
    setUserProfile('default')
    setCopied(false)
  }

  const config = [
    '# MikroTik Hotspot Configuration',
    '# Generated by NetForge',
    '',
    '/ip pool',
    `add name=hotspot-pool ranges=${addressPool}`,
    '',
    '/ip hotspot profile',
    `add name=${profileName || 'default'} hotspot-address=${gateway} dns-name=${dnsName}`,
    '',
    '/ip hotspot',
    `add name=hotspot1 interface=${interfaceName} address-pool=hotspot-pool profile=${profileName || 'default'}`,
    '',
    '/ip hotspot user',
    ...users.map((user) => {
      const uptime = user.limitUptime
        ? ` limit-uptime=${user.limitUptime}`
        : ''

      return `add name=${user.name} password=${user.password} profile=${user.profile}${uptime}`
    }),
  ].join('\n')

  async function copyConfig() {
    await navigator.clipboard.writeText(config)
    setCopied(true)

    setTimeout(() => {
      setCopied(false)
    }, 2000)
  }

  return (
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-pink-500/10 text-pink-400">
            <Globe size={20} />
          </div>

          <div>
            <h2 className="font-semibold text-white">
              Hotspot Generator
            </h2>

            <p className="text-xs text-slate-500">
              Generate MikroTik Hotspot, user profile, pool, and user configuration.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={reset}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs font-medium text-slate-400 transition hover:border-slate-600 hover:text-white"
        >
          <RotateCcw size={14} />
          Reset
        </button>
      </div>

      <div className="grid gap-6 p-5 lg:grid-cols-2">
        <div>
          <h3 className="text-sm font-semibold text-white">
            Hotspot Settings
          </h3>

          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            <input
              value={interfaceName}
              onChange={(event) =>
                setInterfaceName(event.target.value)
              }
              placeholder="Interface e.g. bridge"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={gateway}
              onChange={(event) => setGateway(event.target.value)}
              placeholder="Gateway e.g. 10.10.10.1"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={addressPool}
              onChange={(event) =>
                setAddressPool(event.target.value)
              }
              placeholder="10.10.10.10-10.10.10.254"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500 sm:col-span-2"
            />

            <input
              value={dnsName}
              onChange={(event) => setDnsName(event.target.value)}
              placeholder="hotspot.local"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={profileName}
              onChange={(event) =>
                setProfileName(event.target.value)
              }
              placeholder="Profile name"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />
          </div>

          <div className="mt-6">
            <h3 className="text-sm font-semibold text-white">
              Hotspot Users
            </h3>

            <div className="mt-3 grid gap-3 sm:grid-cols-2">
              <input
                value={username}
                onChange={(event) =>
                  setUsername(event.target.value)
                }
                placeholder="Username"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-500"
              />

              <input
                type="password"
                value={password}
                onChange={(event) =>
                  setPassword(event.target.value)
                }
                placeholder="Password"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-500"
              />

              <input
                value={userProfile}
                onChange={(event) =>
                  setUserProfile(event.target.value)
                }
                placeholder="User profile"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-500"
              />

              <input
                value={limitUptime}
                onChange={(event) =>
                  setLimitUptime(event.target.value)
                }
                placeholder="Limit uptime e.g. 1h"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />
            </div>

            <button
              type="button"
              onClick={addUser}
              className="mt-3 inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
            >
              <Plus size={16} />
              Add User
            </button>
          </div>

          <div className="mt-5 space-y-2">
            {users.map((user) => (
              <div
                key={user.id}
                className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950 px-3 py-3"
              >
                <div className="min-w-0">
                  <p className="text-sm font-medium text-pink-400">
                    {user.name}
                  </p>

                  <p className="mt-1 text-xs text-slate-500">
                    profile {user.profile}
                    {user.limitUptime
                      ? ` · ${user.limitUptime}`
                      : ''}
                  </p>
                </div>

                <button
                  type="button"
                  onClick={() => removeUser(user.id)}
                  className="shrink-0 text-slate-500 transition hover:text-red-400"
                  title="Remove user"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-950">
          <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
            <div>
              <h3 className="text-sm font-semibold text-white">
                Generated RouterOS
              </h3>

              <p className="text-xs text-slate-500">
                Ready to paste into MikroTik RouterOS terminal.
              </p>
            </div>

            <button
              type="button"
              onClick={copyConfig}
              className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-400"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <pre className="max-h-[650px] overflow-auto p-4 font-mono text-xs leading-6 text-slate-300">
            <code>{config}</code>
          </pre>
        </div>
      </div>
    </section>
  )
}

export default HotspotGenerator
