import { useState } from 'react'
import {
  Check,
  Copy,
  Globe,
  Plus,
  RotateCcw,
  Trash2,
} from 'lucide-react'

interface NatRule {
  id: number
  type: 'srcnat' | 'dstnat'
  action: 'masquerade' | 'src-nat' | 'dst-nat'
  chain: 'srcnat' | 'dstnat'
  srcAddress: string
  dstAddress: string
  protocol: 'tcp' | 'udp' | 'any'
  dstPort: string
  toAddress: string
  toPort: string
  outInterface: string
  inInterface: string
}

const defaultRules: NatRule[] = [
  {
    id: 1,
    type: 'srcnat',
    action: 'masquerade',
    chain: 'srcnat',
    srcAddress: '192.168.88.0/24',
    dstAddress: '',
    protocol: 'any',
    dstPort: '',
    toAddress: '',
    toPort: '',
    outInterface: 'ether1',
    inInterface: '',
  },
  {
    id: 2,
    type: 'dstnat',
    action: 'dst-nat',
    chain: 'dstnat',
    srcAddress: '',
    dstAddress: '',
    protocol: 'tcp',
    dstPort: '80',
    toAddress: '192.168.88.10',
    toPort: '80',
    outInterface: '',
    inInterface: 'ether1',
  },
]

function NatGenerator() {
  const [rules, setRules] = useState<NatRule[]>(defaultRules)
  const [type, setType] = useState<'srcnat' | 'dstnat'>('srcnat')
  const [action, setAction] = useState<
    'masquerade' | 'src-nat' | 'dst-nat'
  >('masquerade')
  const [srcAddress, setSrcAddress] = useState('')
  const [dstAddress, setDstAddress] = useState('')
  const [protocol, setProtocol] = useState<'tcp' | 'udp' | 'any'>('any')
  const [dstPort, setDstPort] = useState('')
  const [toAddress, setToAddress] = useState('')
  const [toPort, setToPort] = useState('')
  const [outInterface, setOutInterface] = useState('ether1')
  const [inInterface, setInInterface] = useState('')
  const [copied, setCopied] = useState(false)

  function addRule() {
    const rule: NatRule = {
      id: Date.now(),
      type,
      action:
        type === 'srcnat' && action === 'dst-nat'
          ? 'masquerade'
          : action,
      chain: type,
      srcAddress: srcAddress.trim(),
      dstAddress: dstAddress.trim(),
      protocol,
      dstPort: dstPort.trim(),
      toAddress: toAddress.trim(),
      toPort: toPort.trim(),
      outInterface: outInterface.trim(),
      inInterface: inInterface.trim(),
    }

    setRules((current) => [...current, rule])

    setSrcAddress('')
    setDstAddress('')
    setDstPort('')
    setToAddress('')
    setToPort('')
    setOutInterface(type === 'srcnat' ? 'ether1' : '')
    setInInterface(type === 'dstnat' ? 'ether1' : '')
  }

  function removeRule(id: number) {
    setRules((current) => current.filter((rule) => rule.id !== id))
  }

  function reset() {
    setRules(defaultRules)
    setType('srcnat')
    setAction('masquerade')
    setSrcAddress('')
    setDstAddress('')
    setProtocol('any')
    setDstPort('')
    setToAddress('')
    setToPort('')
    setOutInterface('ether1')
    setInInterface('')
    setCopied(false)
  }

  function buildRule(rule: NatRule) {
    const parts = [
      `/ip firewall nat add chain=${rule.chain}`,
      `action=${rule.action}`,
    ]

    if (rule.srcAddress) {
      parts.push(`src-address=${rule.srcAddress}`)
    }

    if (rule.dstAddress) {
      parts.push(`dst-address=${rule.dstAddress}`)
    }

    if (rule.protocol !== 'any') {
      parts.push(`protocol=${rule.protocol}`)
    }

    if (rule.dstPort) {
      parts.push(`dst-port=${rule.dstPort}`)
    }

    if (rule.outInterface) {
      parts.push(`out-interface=${rule.outInterface}`)
    }

    if (rule.inInterface) {
      parts.push(`in-interface=${rule.inInterface}`)
    }

    if (
      (rule.action === 'src-nat' || rule.action === 'dst-nat') &&
      rule.toAddress
    ) {
      parts.push(`to-addresses=${rule.toAddress}`)
    }

    if (
      (rule.action === 'src-nat' || rule.action === 'dst-nat') &&
      rule.toPort
    ) {
      parts.push(`to-ports=${rule.toPort}`)
    }

    return parts.join(' ')
  }

  const config = [
    '# MikroTik NAT Configuration',
    '# Generated by NetForge',
    '',
    ...rules.map(buildRule),
  ].join('\n')

  async function copyConfig() {
    await navigator.clipboard.writeText(config)
    setCopied(true)

    setTimeout(() => {
      setCopied(false)
    }, 2000)
  }

  const availableActions =
    type === 'srcnat'
      ? (['masquerade', 'src-nat'] as const)
      : (['dst-nat'] as const)

  return (
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-amber-500/10 text-amber-400">
            <Globe size={20} />
          </div>

          <div>
            <h2 className="font-semibold text-white">
              NAT Generator
            </h2>

            <p className="text-xs text-slate-500">
              Generate MikroTik source NAT and destination NAT rules.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={reset}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs font-medium text-slate-400 transition hover:border-slate-600 hover:text-white"
        >
          <RotateCcw size={14} />
          Reset
        </button>
      </div>

      <div className="grid gap-6 p-5 lg:grid-cols-2">
        <div>
          <h3 className="text-sm font-semibold text-white">
            NAT Rule
          </h3>

          <div className="mt-4">
            <span className="mb-2 block text-sm font-medium text-slate-300">
              NAT Type
            </span>

            <div className="grid grid-cols-2 gap-2">
              {[
                ['srcnat', 'Source NAT'],
                ['dstnat', 'Destination NAT'],
              ].map(([value, label]) => (
                <button
                  key={value}
                  type="button"
                  onClick={() => {
                    const nextType = value as 'srcnat' | 'dstnat'
                    setType(nextType)
                    setAction(
                      nextType === 'srcnat' ? 'masquerade' : 'dst-nat',
                    )
                  }}
                  className={[
                    'rounded-lg border px-3 py-2.5 text-sm font-medium transition',
                    type === value
                      ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                      : 'border-slate-700 text-slate-400 hover:text-white',
                  ].join(' ')}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>

          <div className="mt-5">
            <span className="mb-2 block text-sm font-medium text-slate-300">
              Action
            </span>

            <div className="grid grid-cols-2 gap-2">
              {availableActions.map((value) => (
                <button
                  key={value}
                  type="button"
                  onClick={() => setAction(value)}
                  className={[
                    'rounded-lg border px-3 py-2.5 text-sm font-medium transition',
                    action === value
                      ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                      : 'border-slate-700 text-slate-400 hover:text-white',
                  ].join(' ')}
                >
                  {value}
                </button>
              ))}
            </div>
          </div>

          <div className="mt-5 grid gap-3 sm:grid-cols-2">
            <input
              value={srcAddress}
              onChange={(event) => setSrcAddress(event.target.value)}
              placeholder="Source address e.g. 192.168.88.0/24"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={dstAddress}
              onChange={(event) => setDstAddress(event.target.value)}
              placeholder="Destination address"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <select
              value={protocol}
              onChange={(event) =>
                setProtocol(
                  event.target.value as 'tcp' | 'udp' | 'any',
                )
              }
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-500"
            >
              <option value="any">Any Protocol</option>
              <option value="tcp">TCP</option>
              <option value="udp">UDP</option>
            </select>

            <input
              value={dstPort}
              onChange={(event) => setDstPort(event.target.value)}
              placeholder="Destination port e.g. 80"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            {action !== 'masquerade' && (
              <>
                <input
                  value={toAddress}
                  onChange={(event) => setToAddress(event.target.value)}
                  placeholder="To address e.g. 192.168.88.10"
                  className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
                />

                <input
                  value={toPort}
                  onChange={(event) => setToPort(event.target.value)}
                  placeholder="To port e.g. 80"
                  className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
                />
              </>
            )}

            <input
              value={outInterface}
              onChange={(event) => setOutInterface(event.target.value)}
              placeholder="Out interface e.g. ether1"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={inInterface}
              onChange={(event) => setInInterface(event.target.value)}
              placeholder="In interface e.g. ether1"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />
          </div>

          <button
            type="button"
            onClick={addRule}
            className="mt-4 inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
          >
            <Plus size={16} />
            Add NAT Rule
          </button>

          <div className="mt-5 space-y-2">
            {rules.map((rule) => (
              <div
                key={rule.id}
                className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950 px-3 py-3"
              >
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="rounded-md bg-amber-500/10 px-2 py-1 text-xs font-medium text-amber-400">
                      {rule.chain}
                    </span>

                    <span className="font-mono text-xs text-slate-400">
                      {rule.action}
                    </span>
                  </div>

                  <p className="mt-2 truncate font-mono text-xs text-slate-500">
                    {buildRule(rule)}
                  </p>
                </div>

                <button
                  type="button"
                  onClick={() => removeRule(rule.id)}
                  className="shrink-0 text-slate-500 transition hover:text-red-400"
                  title="Remove NAT rule"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-950">
          <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
            <div>
              <h3 className="text-sm font-semibold text-white">
                Generated RouterOS
              </h3>

              <p className="text-xs text-slate-500">
                Ready to paste into MikroTik RouterOS terminal.
              </p>
            </div>

            <button
              type="button"
              onClick={copyConfig}
              className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-400"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <pre className="max-h-[650px] overflow-auto p-4 font-mono text-xs leading-6 text-slate-300">
            <code>{config}</code>
          </pre>
        </div>
      </div>
    </section>
  )
}

export default NatGenerator
