import { useState } from 'react'
import {
  Check,
  Copy,
  Network,
  Plus,
  RotateCcw,
  Trash2,
} from 'lucide-react'

interface OspfNetwork {
  id: number
  network: string
  area: string
}

const defaultNetworks: OspfNetwork[] = [
  {
    id: 1,
    network: '192.168.10.0/24',
    area: '0.0.0.0',
  },
  {
    id: 2,
    network: '192.168.20.0/24',
    area: '0.0.0.0',
  },
]

function OspfGenerator() {
  const [routerId, setRouterId] = useState('1.1.1.1')
  const [instanceName, setInstanceName] = useState('default')
  const [networks, setNetworks] =
    useState<OspfNetwork[]>(defaultNetworks)

  const [network, setNetwork] = useState('')
  const [area, setArea] = useState('0.0.0.0')
  const [passiveInterface, setPassiveInterface] = useState('')
  const [copied, setCopied] = useState(false)

  function addNetwork() {
    const networkValue = network.trim()
    const areaValue = area.trim()

    if (!networkValue || !areaValue) {
      return
    }

    if (
      networks.some(
        (item) =>
          item.network === networkValue &&
          item.area === areaValue,
      )
    ) {
      return
    }

    setNetworks((current) => [
      ...current,
      {
        id: Date.now(),
        network: networkValue,
        area: areaValue,
      },
    ])

    setNetwork('')
    setArea('0.0.0.0')
  }

  function removeNetwork(id: number) {
    setNetworks((current) =>
      current.filter((item) => item.id !== id),
    )
  }

  function reset() {
    setRouterId('1.1.1.1')
    setInstanceName('default')
    setNetworks(defaultNetworks)
    setNetwork('')
    setArea('0.0.0.0')
    setPassiveInterface('')
    setCopied(false)
  }

  const config = [
    '# MikroTik OSPF Configuration',
    '# Generated by NetForge',
    '',
    '/routing ospf instance',
    `set [find name="${instanceName || 'default'}"] router-id=${routerId || '1.1.1.1'}`,
    '',
    '/routing ospf area',
    ...Array.from(
      new Set(networks.map((item) => item.area)),
    ).map(
      (areaValue) =>
        `add name=area-${areaValue.replace(/\./g, '-')} instance=${instanceName || 'default'} area-id=${areaValue}`,
    ),
    '',
    '/routing ospf interface-template',
    ...networks.map((item) => {
      const areaName = `area-${item.area.replace(/\./g, '-')}`

      return `add area=${areaName} networks=${item.network}${passiveInterface.trim() ? ` passive=yes` : ''}`
    }),
    ...(passiveInterface.trim()
      ? [
          '',
          `# Passive interface reference: ${passiveInterface.trim()}`,
        ]
      : []),
  ].join('\n')

  async function copyConfig() {
    await navigator.clipboard.writeText(config)
    setCopied(true)

    setTimeout(() => {
      setCopied(false)
    }, 2000)
  }

  return (
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-500/10 text-indigo-400">
            <Network size={20} />
          </div>

          <div>
            <h2 className="font-semibold text-white">
              OSPF Generator
            </h2>

            <p className="text-xs text-slate-500">
              Generate MikroTik OSPF routing configuration.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={reset}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs font-medium text-slate-400 transition hover:border-slate-600 hover:text-white"
        >
          <RotateCcw size={14} />
          Reset
        </button>
      </div>

      <div className="grid gap-6 p-5 lg:grid-cols-2">
        <div>
          <h3 className="text-sm font-semibold text-white">
            OSPF Settings
          </h3>

          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            <div>
              <label
                htmlFor="mikrotik-ospf-router-id"
                className="mb-2 block text-sm font-medium text-slate-300"
              >
                Router ID
              </label>

              <input
                id="mikrotik-ospf-router-id"
                value={routerId}
                onChange={(event) =>
                  setRouterId(event.target.value)
                }
                placeholder="1.1.1.1"
                className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />
            </div>

            <div>
              <label
                htmlFor="mikrotik-ospf-instance"
                className="mb-2 block text-sm font-medium text-slate-300"
              >
                Instance Name
              </label>

              <input
                id="mikrotik-ospf-instance"
                value={instanceName}
                onChange={(event) =>
                  setInstanceName(event.target.value)
                }
                placeholder="default"
                className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />
            </div>
          </div>

          <div className="mt-6">
            <h3 className="text-sm font-semibold text-white">
              OSPF Networks
            </h3>

            <div className="mt-3 grid gap-3 sm:grid-cols-2">
              <input
                value={network}
                onChange={(event) =>
                  setNetwork(event.target.value)
                }
                placeholder="Network e.g. 192.168.10.0/24"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />

              <input
                value={area}
                onChange={(event) =>
                  setArea(event.target.value)
                }
                placeholder="Area e.g. 0.0.0.0"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />
            </div>

            <button
              type="button"
              onClick={addNetwork}
              className="mt-3 inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
            >
              <Plus size={16} />
              Add Network
            </button>
          </div>

          <div className="mt-5 space-y-2">
            {networks.map((item) => (
              <div
                key={item.id}
                className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950 px-3 py-3"
              >
                <div className="min-w-0">
                  <p className="font-mono text-sm text-indigo-400">
                    {item.network}
                  </p>

                  <p className="mt-1 font-mono text-xs text-slate-500">
                    area {item.area}
                  </p>
                </div>

                <button
                  type="button"
                  onClick={() => removeNetwork(item.id)}
                  className="shrink-0 text-slate-500 transition hover:text-red-400"
                  title="Remove network"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>

          <div className="mt-6">
            <label
              htmlFor="mikrotik-ospf-passive"
              className="mb-2 block text-sm font-medium text-slate-300"
            >
              Passive Interface
            </label>

            <input
              id="mikrotik-ospf-passive"
              value={passiveInterface}
              onChange={(event) =>
                setPassiveInterface(event.target.value)
              }
              placeholder="bridge"
              className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />
          </div>
        </div>

        <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-950">
          <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
            <div>
              <h3 className="text-sm font-semibold text-white">
                Generated RouterOS
              </h3>

              <p className="text-xs text-slate-500">
                Ready to paste into MikroTik RouterOS terminal.
              </p>
            </div>

            <button
              type="button"
              onClick={copyConfig}
              className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-400"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <pre className="max-h-[650px] overflow-auto p-4 font-mono text-xs leading-6 text-slate-300">
            <code>{config}</code>
          </pre>
        </div>
      </div>
    </section>
  )
}

export default OspfGenerator
