import { useState } from 'react'
import {
  Check,
  Copy,
  Gauge,
  Plus,
  RotateCcw,
  Trash2,
} from 'lucide-react'

interface QueueEntry {
  id: number
  name: string
  target: string
  maxLimit: string
  priority: string
}

const defaultQueues: QueueEntry[] = [
  {
    id: 1,
    name: 'Office-PCs',
    target: '192.168.10.0/24',
    maxLimit: '10M/10M',
    priority: '8',
  },
  {
    id: 2,
    name: 'Guest-Network',
    target: '192.168.20.0/24',
    maxLimit: '5M/5M',
    priority: '8',
  },
]

function QueueGenerator() {
  const [queues, setQueues] =
    useState<QueueEntry[]>(defaultQueues)

  const [name, setName] = useState('')
  const [target, setTarget] = useState('')
  const [maxLimit, setMaxLimit] = useState('10M/10M')
  const [priority, setPriority] = useState('8')
  const [burstLimit, setBurstLimit] = useState('')
  const [burstThreshold, setBurstThreshold] = useState('')
  const [burstTime, setBurstTime] = useState('10s')
  const [copied, setCopied] = useState(false)

  function addQueue() {
    const nameValue = name.trim()
    const targetValue = target.trim()
    const limitValue = maxLimit.trim()
    const priorityValue = priority.trim()

    if (
      !nameValue ||
      !targetValue ||
      !limitValue ||
      !priorityValue
    ) {
      return
    }

    if (
      queues.some(
        (queue) => queue.name.toLowerCase() === nameValue.toLowerCase(),
      )
    ) {
      return
    }

    setQueues((current) => [
      ...current,
      {
        id: Date.now(),
        name: nameValue,
        target: targetValue,
        maxLimit: limitValue,
        priority: priorityValue,
      },
    ])

    setName('')
    setTarget('')
    setMaxLimit('10M/10M')
    setPriority('8')
  }

  function removeQueue(id: number) {
    setQueues((current) =>
      current.filter((queue) => queue.id !== id),
    )
  }

  function reset() {
    setQueues(defaultQueues)
    setName('')
    setTarget('')
    setMaxLimit('10M/10M')
    setPriority('8')
    setBurstLimit('')
    setBurstThreshold('')
    setBurstTime('10s')
    setCopied(false)
  }

  const config = [
    '# MikroTik Simple Queue Configuration',
    '# Generated by NetForge',
    '',
    '/queue simple',
    ...queues.map((queue) => {
      const burstOptions =
        burstLimit.trim() &&
        burstThreshold.trim() &&
        burstTime.trim()
          ? ` burst-limit=${burstLimit.trim()} burst-threshold=${burstThreshold.trim()} burst-time=${burstTime.trim()}`
          : ''

      return `add name="${queue.name}" target=${queue.target} max-limit=${queue.maxLimit} priority=${queue.priority}${burstOptions}`
    }),
  ].join('\n')

  async function copyConfig() {
    await navigator.clipboard.writeText(config)
    setCopied(true)

    setTimeout(() => {
      setCopied(false)
    }, 2000)
  }

  return (
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-amber-500/10 text-amber-400">
            <Gauge size={20} />
          </div>

          <div>
            <h2 className="font-semibold text-white">
              Queue Generator
            </h2>

            <p className="text-xs text-slate-500">
              Generate MikroTik Simple Queue bandwidth-management configuration.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={reset}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs font-medium text-slate-400 transition hover:border-slate-600 hover:text-white"
        >
          <RotateCcw size={14} />
          Reset
        </button>
      </div>

      <div className="grid gap-6 p-5 lg:grid-cols-2">
        <div>
          <h3 className="text-sm font-semibold text-white">
            Queue Settings
          </h3>

          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            <input
              value={name}
              onChange={(event) => setName(event.target.value)}
              placeholder="Queue Name"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={target}
              onChange={(event) => setTarget(event.target.value)}
              placeholder="Target e.g. 192.168.10.0/24"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={maxLimit}
              onChange={(event) =>
                setMaxLimit(event.target.value)
              }
              placeholder="Max Limit e.g. 10M/10M"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <select
              value={priority}
              onChange={(event) =>
                setPriority(event.target.value)
              }
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-500"
            >
              <option value="1">Priority 1</option>
              <option value="2">Priority 2</option>
              <option value="3">Priority 3</option>
              <option value="4">Priority 4</option>
              <option value="5">Priority 5</option>
              <option value="6">Priority 6</option>
              <option value="7">Priority 7</option>
              <option value="8">Priority 8</option>
            </select>
          </div>

          <div className="mt-6">
            <h3 className="text-sm font-semibold text-white">
              Burst Settings
            </h3>

            <div className="mt-3 grid gap-3 sm:grid-cols-3">
              <input
                value={burstLimit}
                onChange={(event) =>
                  setBurstLimit(event.target.value)
                }
                placeholder="Burst Limit"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />

              <input
                value={burstThreshold}
                onChange={(event) =>
                  setBurstThreshold(event.target.value)
                }
                placeholder="Threshold"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />

              <input
                value={burstTime}
                onChange={(event) =>
                  setBurstTime(event.target.value)
                }
                placeholder="10s"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />
            </div>

            <p className="mt-2 text-xs text-slate-500">
              Leave the burst fields empty to generate a standard
              Simple Queue.
            </p>
          </div>

          <button
            type="button"
            onClick={addQueue}
            className="mt-5 inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
          >
            <Plus size={16} />
            Add Queue
          </button>

          <div className="mt-5 space-y-2">
            {queues.map((queue) => (
              <div
                key={queue.id}
                className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950 px-3 py-3"
              >
                <div className="min-w-0">
                  <p className="text-sm font-semibold text-amber-400">
                    {queue.name}
                  </p>

                  <p className="mt-1 font-mono text-xs text-slate-500">
                    {queue.target} · {queue.maxLimit} · priority{' '}
                    {queue.priority}
                  </p>
                </div>

                <button
                  type="button"
                  onClick={() => removeQueue(queue.id)}
                  className="shrink-0 text-slate-500 transition hover:text-red-400"
                  title="Remove queue"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-950">
          <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
            <div>
              <h3 className="text-sm font-semibold text-white">
                Generated RouterOS
              </h3>

              <p className="text-xs text-slate-500">
                Ready to paste into MikroTik RouterOS terminal.
              </p>
            </div>

            <button
              type="button"
              onClick={copyConfig}
              className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-400"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <pre className="max-h-[650px] overflow-auto p-4 font-mono text-xs leading-6 text-slate-300">
            <code>{config}</code>
          </pre>
        </div>
      </div>
    </section>
  )
}

export default QueueGenerator
