import { useState } from 'react'
import {
  Check,
  Copy,
  Network,
  Plus,
  RotateCcw,
  Trash2,
} from 'lucide-react'

interface RouteEntry {
  id: number
  dstAddress: string
  gateway: string
  distance: string
  comment: string
}

const defaultRoutes: RouteEntry[] = [
  {
    id: 1,
    dstAddress: '192.168.20.0/24',
    gateway: '192.168.10.1',
    distance: '1',
    comment: 'Servers Network',
  },
  {
    id: 2,
    dstAddress: '10.10.0.0/16',
    gateway: '192.168.10.254',
    distance: '1',
    comment: 'Remote Network',
  },
]

function StaticRouteGenerator() {
  const [routes, setRoutes] = useState<RouteEntry[]>(defaultRoutes)
  const [dstAddress, setDstAddress] = useState('')
  const [gateway, setGateway] = useState('')
  const [distance, setDistance] = useState('1')
  const [comment, setComment] = useState('')
  const [copied, setCopied] = useState(false)

  function addRoute() {
    const destination = dstAddress.trim()
    const gatewayValue = gateway.trim()
    const distanceValue = distance.trim()
    const commentValue = comment.trim()

    if (!destination || !gatewayValue || !distanceValue) {
      return
    }

    if (
      routes.some(
        (route) =>
          route.dstAddress === destination &&
          route.gateway === gatewayValue,
      )
    ) {
      return
    }

    setRoutes((current) => [
      ...current,
      {
        id: Date.now(),
        dstAddress: destination,
        gateway: gatewayValue,
        distance: distanceValue,
        comment: commentValue,
      },
    ])

    setDstAddress('')
    setGateway('')
    setDistance('1')
    setComment('')
  }

  function removeRoute(id: number) {
    setRoutes((current) =>
      current.filter((route) => route.id !== id),
    )
  }

  function reset() {
    setRoutes(defaultRoutes)
    setDstAddress('')
    setGateway('')
    setDistance('1')
    setComment('')
    setCopied(false)
  }

  const config = [
    '# MikroTik Static Routes',
    '# Generated by NetForge',
    '',
    '/ip route',
    ...routes.map((route) => {
      const commentPart = route.comment
        ? ` comment="${route.comment.replace(/"/g, '')}"`
        : ''

      return `add dst-address=${route.dstAddress} gateway=${route.gateway} distance=${route.distance}${commentPart}`
    }),
  ].join('\n')

  async function copyConfig() {
    await navigator.clipboard.writeText(config)
    setCopied(true)

    setTimeout(() => {
      setCopied(false)
    }, 2000)
  }

  return (
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-sky-500/10 text-sky-400">
            <Network size={20} />
          </div>

          <div>
            <h2 className="font-semibold text-white">
              Static Route Generator
            </h2>

            <p className="text-xs text-slate-500">
              Generate MikroTik static routing configuration.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={reset}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs font-medium text-slate-400 transition hover:border-slate-600 hover:text-white"
        >
          <RotateCcw size={14} />
          Reset
        </button>
      </div>

      <div className="grid gap-6 p-5 lg:grid-cols-2">
        <div>
          <h3 className="text-sm font-semibold text-white">
            Route Settings
          </h3>

          <div className="mt-4 grid gap-3">
            <input
              value={dstAddress}
              onChange={(event) => setDstAddress(event.target.value)}
              placeholder="Destination e.g. 192.168.20.0/24"
              className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={gateway}
              onChange={(event) => setGateway(event.target.value)}
              placeholder="Gateway e.g. 192.168.10.1"
              className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <div className="grid gap-3 sm:grid-cols-2">
              <input
                type="number"
                min="1"
                max="255"
                value={distance}
                onChange={(event) => setDistance(event.target.value)}
                placeholder="Distance"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
              />

              <input
                value={comment}
                onChange={(event) => setComment(event.target.value)}
                placeholder="Comment"
                className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-500"
              />
            </div>
          </div>

          <button
            type="button"
            onClick={addRoute}
            className="mt-3 inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
          >
            <Plus size={16} />
            Add Route
          </button>

          <div className="mt-5 space-y-2">
            {routes.map((route) => (
              <div
                key={route.id}
                className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950 px-3 py-3"
              >
                <div className="min-w-0">
                  <p className="font-mono text-sm text-sky-400">
                    {route.dstAddress}
                  </p>

                  <p className="mt-1 font-mono text-xs text-slate-500">
                    via {route.gateway} · distance {route.distance}
                  </p>

                  {route.comment && (
                    <p className="mt-1 text-xs text-slate-600">
                      {route.comment}
                    </p>
                  )}
                </div>

                <button
                  type="button"
                  onClick={() => removeRoute(route.id)}
                  className="shrink-0 text-slate-500 transition hover:text-red-400"
                  title="Remove route"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-950">
          <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
            <div>
              <h3 className="text-sm font-semibold text-white">
                Generated RouterOS
              </h3>

              <p className="text-xs text-slate-500">
                Ready to paste into MikroTik RouterOS terminal.
              </p>
            </div>

            <button
              type="button"
              onClick={copyConfig}
              className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-400"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <pre className="max-h-[650px] overflow-auto p-4 font-mono text-xs leading-6 text-slate-300">
            <code>{config}</code>
          </pre>
        </div>
      </div>
    </section>
  )
}

export default StaticRouteGenerator
