import { useState } from 'react'
import {
  Check,
  Copy,
  Network,
  Plus,
  RotateCcw,
  Trash2,
} from 'lucide-react'

interface VlanEntry {
  id: number
  name: string
  interfaceName: string
  mtu: string
}

const defaultVlans: VlanEntry[] = [
  {
    id: 10,
    name: 'USERS',
    interfaceName: 'bridge',
    mtu: '1500',
  },
  {
    id: 20,
    name: 'SERVERS',
    interfaceName: 'bridge',
    mtu: '1500',
  },
  {
    id: 30,
    name: 'MANAGEMENT',
    interfaceName: 'bridge',
    mtu: '1500',
  },
]

function VlanGenerator() {
  const [vlans, setVlans] = useState<VlanEntry[]>(defaultVlans)
  const [vlanId, setVlanId] = useState('')
  const [name, setName] = useState('')
  const [interfaceName, setInterfaceName] = useState('bridge')
  const [mtu, setMtu] = useState('1500')
  const [bridgeName, setBridgeName] = useState('bridge')
  const [vlanFiltering, setVlanFiltering] = useState(true)
  const [copied, setCopied] = useState(false)

  function addVlan() {
    const id = Number(vlanId)
    const nameValue = name.trim().toUpperCase()
    const interfaceValue = interfaceName.trim()
    const mtuValue = mtu.trim()

    if (
      !Number.isInteger(id) ||
      id < 1 ||
      id > 4094 ||
      !nameValue ||
      !interfaceValue ||
      !mtuValue
    ) {
      return
    }

    if (vlans.some((vlan) => vlan.id === id)) {
      return
    }

    setVlans((current) => [
      ...current,
      {
        id,
        name: nameValue,
        interfaceName: interfaceValue,
        mtu: mtuValue,
      },
    ])

    setVlanId('')
    setName('')
    setInterfaceName('bridge')
    setMtu('1500')
  }

  function removeVlan(id: number) {
    setVlans((current) => current.filter((vlan) => vlan.id !== id))
  }

  function reset() {
    setVlans(defaultVlans)
    setVlanId('')
    setName('')
    setInterfaceName('bridge')
    setMtu('1500')
    setBridgeName('bridge')
    setVlanFiltering(true)
    setCopied(false)
  }

  const config = [
    '# MikroTik VLAN Configuration',
    '# Generated by NetForge',
    '',
    `/interface bridge`,
    `set [find name="${bridgeName || 'bridge'}"] vlan-filtering=${vlanFiltering ? 'yes' : 'no'}`,
    '',
    ...vlans.map(
      (vlan) =>
        `/interface vlan add name=vlan${vlan.id} interface=${vlan.interfaceName} vlan-id=${vlan.id} mtu=${vlan.mtu}`,
    ),
    '',
    '/interface bridge vlan',
    ...vlans.map(
      (vlan) =>
        `add bridge=${bridgeName || 'bridge'} tagged=${vlan.interfaceName} vlan-ids=${vlan.id}`,
    ),
  ].join('\n')

  async function copyConfig() {
    await navigator.clipboard.writeText(config)
    setCopied(true)

    setTimeout(() => {
      setCopied(false)
    }, 2000)
  }

  return (
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-violet-500/10 text-violet-400">
            <Network size={20} />
          </div>

          <div>
            <h2 className="font-semibold text-white">
              VLAN Generator
            </h2>

            <p className="text-xs text-slate-500">
              Generate MikroTik VLAN interfaces and bridge VLAN configuration.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={reset}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs font-medium text-slate-400 transition hover:border-slate-600 hover:text-white"
        >
          <RotateCcw size={14} />
          Reset
        </button>
      </div>

      <div className="grid gap-6 p-5 lg:grid-cols-2">
        <div>
          <h3 className="text-sm font-semibold text-white">
            VLAN Settings
          </h3>

          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            <input
              type="number"
              min="1"
              max="4094"
              value={vlanId}
              onChange={(event) => setVlanId(event.target.value)}
              placeholder="VLAN ID"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={name}
              onChange={(event) => setName(event.target.value)}
              placeholder="VLAN Name"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              value={interfaceName}
              onChange={(event) =>
                setInterfaceName(event.target.value)
              }
              placeholder="Interface e.g. bridge"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />

            <input
              type="number"
              min="576"
              max="65535"
              value={mtu}
              onChange={(event) => setMtu(event.target.value)}
              placeholder="MTU"
              className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />
          </div>

          <button
            type="button"
            onClick={addVlan}
            className="mt-3 inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
          >
            <Plus size={16} />
            Add VLAN
          </button>

          <div className="mt-5 space-y-2">
            {vlans.map((vlan) => (
              <div
                key={vlan.id}
                className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-950 px-3 py-3"
              >
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-mono text-sm text-violet-400">
                      VLAN {vlan.id}
                    </span>

                    <span className="text-sm text-slate-300">
                      {vlan.name}
                    </span>
                  </div>

                  <p className="mt-1 font-mono text-xs text-slate-500">
                    {vlan.interfaceName} · MTU {vlan.mtu}
                  </p>
                </div>

                <button
                  type="button"
                  onClick={() => removeVlan(vlan.id)}
                  className="shrink-0 text-slate-500 transition hover:text-red-400"
                  title="Remove VLAN"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>

          <div className="mt-6">
            <label
              htmlFor="mikrotik-bridge-name"
              className="mb-2 block text-sm font-medium text-slate-300"
            >
              Bridge Name
            </label>

            <input
              id="mikrotik-bridge-name"
              value={bridgeName}
              onChange={(event) => setBridgeName(event.target.value)}
              placeholder="bridge"
              className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 font-mono text-sm text-white outline-none focus:border-emerald-500"
            />
          </div>

          <div className="mt-5">
            <span className="mb-2 block text-sm font-medium text-slate-300">
              VLAN Filtering
            </span>

            <div className="grid grid-cols-2 gap-2">
              <button
                type="button"
                onClick={() => setVlanFiltering(true)}
                className={[
                  'rounded-lg border px-3 py-2.5 text-sm font-medium transition',
                  vlanFiltering
                    ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                    : 'border-slate-700 text-slate-400 hover:text-white',
                ].join(' ')}
              >
                Enabled
              </button>

              <button
                type="button"
                onClick={() => setVlanFiltering(false)}
                className={[
                  'rounded-lg border px-3 py-2.5 text-sm font-medium transition',
                  !vlanFiltering
                    ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400'
                    : 'border-slate-700 text-slate-400 hover:text-white',
                ].join(' ')}
              >
                Disabled
              </button>
            </div>
          </div>
        </div>

        <div className="min-w-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-950">
          <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3">
            <div>
              <h3 className="text-sm font-semibold text-white">
                Generated RouterOS
              </h3>

              <p className="text-xs text-slate-500">
                Ready to paste into MikroTik RouterOS terminal.
              </p>
            </div>

            <button
              type="button"
              onClick={copyConfig}
              className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-400"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <pre className="max-h-[650px] overflow-auto p-4 font-mono text-xs leading-6 text-slate-300">
            <code>{config}</code>
          </pre>
        </div>
      </div>
    </section>
  )
}

export default VlanGenerator
